### ISSUE TITLE
tcp://arangodb-proxy.marathon.mesos:8529 is not rechable

### ISSUE THREAD

**Issue by Rao-Sahab** [arangodb/arangodb-mesos-haproxy#1]
I have a Arangodb setup on top of dcos. DCOS setup is with 1 master and 6 nodes and Arangodb have 3 coordinators 3 agencies and 5 dbservers. I have everything in place but to make thing highly available(In case coordinator shift from one server to other), I want to use load balancer. I used the following commands to install haproxy from my dcos master.

$ git clone https://github.com/arangodb/arangodb-mesos-haproxy
$ cd arangodb-mesos-haproxy
$ dcos marathon app add marathon.json

I felt no updates are required in marathon.json so I kept it as it is. With the execution of the above commands I have 3 services running under arangodb-proxy in DCOS. If I use IP:port(8529) than Arangodb web UI shows up. But the endpoint "tcp://arangodb-proxy.marathon.mesos:8529" is not rechable.

**Comment by m0ppers** [comment]
Just to make things crystal clear: You did try to reach arangodb-proxy.marathon.mesos:8529 from inside your cluster (i.e. mesos-dns was available) and not from the outside (where mesos-dns is of course not reachable)?

**Comment by Rao-Sahab** [comment]
Yes I tried reaching the endpoint mentioned from the cluster where mesos-dns is available.

**Comment by m0ppers** [comment]
Hummm...I just retested if everything was working ok.

I deployed a standard dc/os using AWS. Then I deployed a standard arangodb via the UI. Then I deployed the haproxy using the UI.

Then I sshed to one of the mesos agents:

```
core@ip-10-0-0-223 ~ $ host arangodb-proxy.marathon.mesos
arangodb-proxy.marathon.mesos has address 10.0.3.31
arangodb-proxy.marathon.mesos has address 10.0.0.28
arangodb-proxy.marathon.mesos has address 10.0.0.222
core@ip-10-0-0-223 ~ $ curl arangodb-proxy.marathon.mesos:8529/_api/version
{"server":"arango","version":"3.1.11","license":"community"}
core@ip-10-0-0-223 ~ $ docker run -it --entrypoint=/bin/bash arangodb/arangodb:3.1.11
root@7795457b26cb:/# arangosh --server.endpoint tcp://arangodb-proxy.marathon.mesos:8529
Please specify a password: 

                                       _     
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__  
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \ 
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/                 

arangosh (ArangoDB 3.1.11 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1t  3 May 2016)
Copyright (c) ArangoDB GmbH

Pretty printing values.
Connected to ArangoDB 'http+tcp://arangodb-proxy.marathon.mesos:8529' version: 3.1.11 [server], database: '_system', username: 'root'

Type 'tutorial' for a tutorial or 'help' to see common examples
arangodb-proxy.marathon.mesos:8529@_system> db._collections()
[ 
  [ArangoCollection 100031, "_apps" (type document, status loaded)], 
  [ArangoCollection 100014, "_aqlfunctions" (type document, status loaded)], 
  [ArangoCollection 100025, "_frontend" (type document, status loaded)], 
  [ArangoCollection 100001, "_graphs" (type document, status loaded)], 
  [ArangoCollection 100029, "_jobs" (type document, status loaded)], 
  [ArangoCollection 100007, "_modules" (type document, status loaded)], 
  [ArangoCollection 100027, "_queues" (type document, status loaded)], 
  [ArangoCollection 100009, "_routing" (type document, status loaded)], 
  [ArangoCollection 100019, "_statistics" (type document, status loaded)], 
  [ArangoCollection 100022, "_statistics15" (type document, status loaded)], 
  [ArangoCollection 100016, "_statisticsRaw" (type document, status loaded)], 
  [ArangoCollection 100003, "_users" (type document, status loaded)] 
]

arangodb-proxy.marathon.mesos:8529@_system> 
```

What am I missing?

**Comment by Rao-Sahab** [comment]
My apologies, mistake was mine and been rectified. Thanks for your time and effort.

**Comment by m0ppers** [comment]
no worries :)
