### ISSUE TITLE
arangodb-proxy.marathon.mesos:8529 refuse to connect in DCOS1.9.0

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb-mesos-haproxy#2]
@m0ppers Hi friend, I install a cluster in the dcos1.9.0, arangodb3 work fine in the cluster. Then I apply the haproxy, but it desn't work well.And I can ping the web IP in the cluster. Is there any difference between DCOS1.9 and DCOS1.8, how can i adjust the configuration?Thanks.

[root@localhost ~]# ping arangodb-proxy.marathon.mesos
PING arangodb-proxy.marathon.mesos (192.168.30.15) 56(84) bytes of data.
64 bytes from 192.168.30.15 (192.168.30.15): icmp_seq=1 ttl=64 time=0.276 ms
64 bytes from 192.168.30.15 (192.168.30.15): icmp_seq=2 ttl=64 time=0.266 ms
^C
--- arangodb-proxy.marathon.mesos ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.266/0.271/0.276/0.005 ms

![image](https://cloud.githubusercontent.com/assets/25783698/25112945/e996b578-2426-11e7-8cb5-236e8ec3aa0f.png)

**Comment by hellomanjack** [comment]
I get the error when I use "http.get()" in the docker . I wonder what cause it in the docker.

**Comment by m0ppers** [comment]
It seems that the mesos dns has 127.0.0.1 for the arangodb framework...

can you do a `ping arangodb3.mesos`?

**Comment by hellomanjack** [comment]
@m0ppers sorry reply so late, I has changed to DCOS1.8.8. Thanks, good man !
